# Generated by Django 4.1.2 on 2022-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.IntegerField(null=True),
        ),
    ]
