# Generated by Django 4.1.2 on 2022-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_twitteruser_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='status_user',
            field=models.CharField(choices=[('New', 'New'), ('Ready to Scrape', 'Ready to Scrape'), ('Failed to Scrape', 'Failed to Scrape'), ('Complete', 'Complete')], default='New', help_text='The status of scrape_user', max_length=26),
        ),
    ]
