# Generated by Django 4.1.2 on 2022-10-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_twitteruser_status_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='twitteruser',
            table='twitter_user',
        ),
    ]
